### PR TITLE
fix(build): disable next export

### PR DESCRIPTION
**Pull request by kahboom**

### CODE REVIEW

**Review by JasonPowr — APPROVED** [review]
/lgtm

**Review by lance — COMMENTED** [review]
/lgtm

**Comment by kahboom** [comment]
@lance @JasonPowr did we want to wait for the Konflux build to finish before merging? could be a while, I think about 40 mins

**Comment by JasonPowr** [comment]
I see no harm in merging, The image built and the Clair-scan came back fine :), any changes needed can be followed up :) 
Ill go ahead and merge

**Pull request merged**
